# Page settings
baseurl = "www.the-o.dev"
title = "The-o Dev"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Theo Delfieu"
  description = "Freelance software developer, this website is a summary of my activity"
  email = "theo.delfieu@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "The-o dev"
    home = "Home"
    work = "Work"
    # testimonials = "Testimonials"
    services = "Technologies"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Freelance Software Developer"
    subtitle = 'Passionate about software programming, working as a freelance. <br/> This is my personal website to show my different work experiences and skills'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Understand quickly your functionnal requirement, give you a technical analasys, advices and elaborate a software architecture that will match your needs."
    url = "#"
    # button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Build your software from scratch, add a new feature to an existing project, help you maintain a platform or bug fixings."
    url = "#"
    # button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Manage the deployement of the web application, testing, best practictes to realease the highest software quality possible, deal with high traffic and hosting of your website/application"
    url = "#"
    # button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  # [params.intro.video]
  #   enable = true
  #   title = "Watch the video"
  #   icon = "icon-play2"
  #   url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "This is a not exhaustive list of project I have been involved in."
    # footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "myPLM.jpeg"
      alt = "myPLM"
      title = "myPLM"
      subtitle = "Product Lifecycle Management Web Application"

    [[params.work.row]]
      img = "seeticketsus.jpeg"
      alt = "Seetickets US"
      title = "Seetickets US"
      subtitle = "Ticketing selling platform"      

    [[params.work.row]]
      img = "artung.png"
      alt = "Artung"
      title = "ArtUNG"
      subtitle = "Mobile Art interaction application"

    [[params.work.row]]
      img = "netia.jpg"
      alt = "Netia"
      title = "Netia Media Assist"
      subtitle = "Media Asset Management software"

    [[params.work.row]]
      img = "balea.jpg"
      alt = "Balea"
      title = "Balea"
      subtitle = "Logistic weighting solution"      

    [[params.work.row]]
      img = "laregion.jpg"
      alt = "Region Occitanie"
      title = "Public Data Management"
      subtitle = "Public data business intelligence"

  # Testimonials section
  # [params.testimonials]
  #   enable = true
  #   title = "Testimonials"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  #   [[params.testimonials.item]]
  #     quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
  #     person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #     img = "person1.jpg"
  #     alt = "Person1"

  #   [[params.testimonials.item]]
  #     quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
  #     person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #     img = "person2.jpg"
  #     alt = "Person2"

  #   [[params.testimonials.item]]
  #     quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
  #     person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
  #     img = "person3.jpg"
  #     alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Technologies"
    description = "A summary of technologies I have been using"

    [[params.services.item]]
      title = "Programming"
      description = "C# (.NET(core), ASP, Web API) - JavaScript - TypeScript - Node.JS - SQL - NoSQL - YAML - JSON - XML - HTTP - CSS3 - Visual Basic"
      icon = "icon-terminal"

    [[params.services.item]]
      title = "Data"
      description = "SQL and NoSQL Databases (SQL Server, PostGre, MongoDB, DynamoDB), ElasticSearch, Redis, Talend, Qliksense, Qlikview"
      icon = "icon-database"

    [[params.services.item]]
      title = "DevOps"
      description = "GIT - Azure DevOps - Amazon Web Services - Google Cloud Platform - Docker - TeamCity - Jenkins"
      icon = "icon-cogs"

      [[params.services.item]]
      title = "Miscellaneous"
      description = "TDD - Best Practices - Apache - NGinx - IIS - Unix - Windows - Project Management"      
      icon = "icon-monitor"

  # # About section
  # [params.about]
  #   enable = true
  #   title = "About"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  #   [[params.about.item]]
  #     name = "Jean Smith"
  #     position = "Web Designer"
  #     description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
  #     img = "person1.jpg"
  #     alt = "Person1"
  #     social = [
  #       ["icon-twitter", "#"],
  #       ["icon-facebook", "#"],
  #       ["icon-linkedin", "#"]
  #     ]

  #   [[params.about.item]]
  #     name = "Rob Smith"
  #     position = "Web Developer"
  #     description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
  #     img = "person2.jpg"
  #     alt = "Person2"
  #     social = [
  #       ["icon-twitter", "#"],
  #       ["icon-facebook", "#"],
  #       ["icon-github", "#"]
  #     ]

  #   [[params.about.item]]
  #     name = "Larry Ben"
  #     position = "Web Designer"
  #     description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
  #     img = "person3.jpg"
  #     alt = "Person3"
  #     social = [
  #       ["icon-twitter", "#"],
  #       ["icon-facebook", "#"],
  #       ["icon-dribbble", "#"]
  #     ]      

  # # Counters section
  # [params.counters]
  #   enable = true
  #   title = "Stats"
  #   background = "full_image_1.jpg"

  #   [[params.counters.item]]
  #     description = "Finished projects"
  #     icon = "icon-briefcase"
  #     from = 0
  #     to = 89
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Lines of code"
  #     icon = "icon-code"
  #     from = 0
  #     to = 2343409
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Cups of coffee"
  #     icon = "icon-cup"
  #     from = 0
  #     to = 1302
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Happy clients"
  #     icon = "icon-people"
  #     from = 0
  #     to = 52
  #     interval = 50
  #     speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = ""
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Montpellier, France"],
        ["icon-phone", "(+33) 6 76 92 21 87"],
        ["icon-envelope", "theo.delfieu@gmail.com"],
        ["icon-globe", '<a href="https://www.the-o.dev/" target="_blank">the-o.dev</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    # copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a>'
    # links = [
    #     ["icon-twitter", "#twitter"],
    #     ["icon-facebook", "#facebook"],
    #     ["icon-youtube", "#youtube"]
    #   ]


[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://www.the-o.dev"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true


